spring:
    profiles: eureka3

server:
    port: 8763

eureka:
    instance:
        hostname: eureka3
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/

