server:
    port: 8081

eureka:
    healthcheck:
          enabled: true
    client:
      serviceUrl:
          defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka,http://eureka3:8763/eureka